# Generated by Django 5.0.4 on 2024-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='valid_time',
            field=models.CharField(max_length=4),
        ),
    ]
